default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: javier
  password: inves
  host: localhost
  port: 5432

development:
  <<: *default
  database: db_peluqueria

test:
  <<: *default
  database: db_peluqueria

production:
  <<: *default
  database: db_peluqueria
  username: javier
  password: inves
  host: localhost
